export { default as App } from './App/AppContainer'
export { default as Slice } from './Slice/SliceComponent'
export { default as Intro } from './Intro/IntroComponent'
export { default as Bio } from './Bio/BioComponent'
export { default as Skills } from './Skills/SkillsComponent'