export { default as App } from './App/App'
export { default as Slice } from './Slice/Slice'
export { default as Intro } from './Intro/Intro'
export { default as Strip } from './Strip/Strip'
export { default as Grid } from './Grid/Grid'